server:
  port: 9191
#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE
#      routes:
#      - id: USER-SERVICE
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/users/** 
#      
#      - id: TEACHER-SERVICE
#        uri: lb://TEACHER-SERVICE
#        predicates:
#        - Path=/teachers/**  
#       
#      - id: SCHOOL-SERVICE
#        uri: lb://SCHOOL-SERVICE
#        predicates:
#        - Path=/schools/**  
#      
#      - id: STUDENT-SERVICE
#        uri: lb://STUDENT-SERVICE
#        predicates:
#        - Path=/students/** 
#        
#      - id: AVATAR-SERVICE
#        uri: lb://AVATAR-SERVICE
#        predicates:
#        - Path=/avatars/** 
#        
#      - id: SECURITY-SERVICE
#        uri: lb://SECURITY-SERVICE
#        predicates:
#        - Path=/oauth/** 
#        
#      - id: LOGIN-SERVICE
#        uri: lb://LOGIN-SERVICE
#        predicates:
#        - Path=/login/**           
#
#eureka: 
# client:
#   register-with-eureka: true
#   fetch-registry: true
#   service-url:
#      defaultZone : http://localhost:8761/eureka/
# instance:
#   hostname: localhost   