server:
  port: 8087

spring:
  application:
    name: SECURITYSERVICE   

#security:
#  oauth2:
#    resource:
#     token-info-uri: http://localhost:8087/oauth/check_token
#    client:
#     client-id: client
#     client-secret: secret   
#
#eureka:
#  client:
#   register-with-eureka: true
#   fetch-registry: true
#   service-url:
#           defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost      