spring:
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: miuwaafinal@gmail.com
    password: 7D1B1A2B6684A6A90B110CF2D1690BC2DC9B
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
email:
  from: miuwaafinal@gmail.com