server:
  port: 8085
  
#spring:
#  application:
#    name: AVATAR-SERVICE
#        
#
#eureka: 
# client:
#   register-with-eureka: true
#   fetch-registry: true
#   service-url:
#      defaultZone : http://localhost:8761/eureka/
# instance:
#   hostname: localhost

security:
  oauth2:
    resource:
     token-info-uri: http://localhost:8087/oauth/check_token
    client:
     client-id: client
     client-secret: secret 
   
   